### ISSUE TITLE
The robot arm doesn't pick the boxes

### ISSUE THREAD

**Issue by Egehae** [lihuang3/ur5_notebook#24]
Hi, lihuang. I'm new to ROS and interested in your project,
because I wanna simulate picking process with vacuum gripper.

But when I launch `initialize.launch`, the robot arm doesn't pick the red boxes though it detects them.
It just goes to the placing position with empty hand and stays still.

I think the error messages involved are these.

[ INFO] [1591681700.942636701, 17.686000000]: Received request to compute Cartesian path
[ERROR] [1591681700.942913192, 17.686000000]: TF Problem: Invalid argument "/base_link" passed to lookupTransform argument target_frame in tf2 frame_ids cannot start with a '/' like:
[ERROR] [1591681700.942986402, 17.686000000]: Error encountered transforming waypoints to frame 'world'
[INFO] [1591681700.943591, 17.687000]: Path planning failed

As I'm using melodic, I thought there could be some errors but can you help me with it?

![Screenshot from 2020-06-09 00-00-58](https://user-images.githubusercontent.com/66660293/84108167-8433fe80-aa5a-11ea-8317-a7223c107371.png)
![Screenshot from 2020-06-09 00-01-04](https://user-images.githubusercontent.com/66660293/84108170-85652b80-aa5a-11ea-9ab7-033537906aeb.png)

**Comment by lihuang3** [comment]
I had similar issues before. You can just try restarting the program/ROS-gazebo. If it doesn't work, it might be the ROS version problem as it was only tested on Kinetic.

**Comment by Egehae** [comment]
I solved it! The problem was in `ur5_mp.py`. I don't know whether it's because of the version difference, but I fixed the value of `reference_frame = "/base_link"` to `"base_link"` and now the simulation works well. Thanks for this great work.

**Comment by JinchuanMa** [comment]
> I solved it! The problem was in `ur5_mp.py`. I don't know whether it's because of the version difference, but I fixed the value of `reference_frame = "/base_link"` to `"base_link"` and now the simulation works well. Thanks for this great work.

Hello, can you directly change the code from "/base_link" to "base_link"?

**Comment by JinchuanMa** [comment]
> I solved it! The problem was in `ur5_mp.py`. I don't know whether it's because of the version difference, but I fixed the value of `reference_frame = "/base_link"` to `"base_link"` and now the simulation works well. Thanks for this great work.

hello，Can share your open source project code？
