### ISSUE TITLE
Gazebo vacuum gripper plugin

### ISSUE THREAD

**Issue by st99315** [lihuang3/ur5_notebook#4]
Hi! I have seen your video of pick and place demo using UR5 and vacuum gripper from youtube.
This is a nice work and we are very interesting!!

Recently we want to use vacuum gripper in gazebo simulator, but we get some problem. 

We can load plugin to simulator and trigger it, but  sometime vacuum gripper can’t grasp object in gazebo.

We’d like to ask you some questions:
1. What reason make you increase amount of vacuum gripper becoming nine grippers?
2. What kind of help would do this?
3. What are the functions of the following two tags for gazebo vacuum gripper plugin?
```
<maxDistance>0.05</maxDistance>
<minDistance>0.01</minDistance>
```

Thanks for providing useful example on github!

**Comment by lihuang3** [comment]
@st99315 Thanks for your interest!

(1) & (2)  It seems that each vacuum gripper only provides limited force to lift object. We spent two or three days investigating the vacuum gripper module, but did not figure out an elegant way to handle even a very light box. So we just use 9 of them to make sure we have enough force and meanwhile reduce the weight of objects.
(3)  Looks like these are the effective range for the vacuum gripper.  I'm not sure, but I have to say, the vacuum gripper module is not well described, and they did not behave as well as what they meant to.

I suggest you refer to the following websites, as they discussed some interesting topics about the module:
https://answers.ros.org/question/243080/need-help-to-trigger-the-vacuum-gripper/
https://github.com/ros-simulation/gazebo_ros_pkgs/pull/389
http://answers.gazebosim.org/question/6306/how-to-simulate-vacuum-clamping/

**Comment by bharatm11** [comment]
Hi @lihuang3 
Do you think just adding the vacuum grippers to the URDF and calling the appropriate service from the terminal will do the job? What is the role of ur5_gripper.py ?
Thanks,
Bharat Mathur

**Comment by lihuang3** [comment]
Hi @bharatm11, of course you can just call the gripper service from a terminal, and it would work as mentioned in the above links. `ur5_gripper.py` subscribes ‘cxy1’ (
https://github.com/lihuang3/ur5_ROS-Gazebo/blob/29c2a23acbb31fa4648f1a6d1bfdcc293c49a8c4/ur5_gripper.py#L237), so the gripper can be turned on as the end-effector gets close enough to the object and be turned off as the end-effector reaches the target position. `ur5_gripper.py` was developed for automatic gripper operation based on end-effector status. 

Thank you,

Li

**Comment by bharatm11** [comment]
@lihuang3 Thank you very much for your reply! 
I tried using your URDF to spawn the UR5 on Gazebo and called the services to turn the gripper on using the terminal but it fails to pick the object up. It works when I try to run your launch file.
I even made sure that the gripper feedback topics /ur5/vacuum_gripper/grasping were true when I called the service.
What else do you think I should try?

**Comment by lihuang3** [comment]
@bharatm11 How many grippers did you turn on? One or two probably won’t make it happen, as the vacuum force is very limited. You might need about 5 grippers for a red box in this project. Also please make sure that the grippers have fully contact with the target object surface.

**Comment by bharatm11** [comment]
@lihuang3 
I made it work on my KUKA IIWA! Thanks a ton for your support! :)

Best,
Bharat Mathur

**Comment by lihuang3** [comment]
@bharatm11 Sounds great!

**Comment by garethByers** [comment]
I have used this gripper and have added it to the ur5_robot however, it still wont grasp when they are set  to on. i can look in the topic list and they are there and are set to on in the gazebo terminal but they still do not move the object. Is there any advice you have?
