### ISSUE TITLE
How can I get the same goal as gif

### ISSUE THREAD

**Issue by weiwuhuhu** [lihuang3/ur5_notebook#5]
Hello Lihuang：
      I had followed your steps and installed all the package which in the readme, but how can I get the same effect after I had executed the step of "roslaunch ur5_notebook initialize.launch".But the ur5 remained static, it can't grasp the red box.

**Comment by weiwuhuhu** [comment]
I got it, one step i missed.Thank you LiHuang, you are so cool!!!

**Comment by lihuang3** [comment]
@weiwuhuhu Thank you, enjoy!

**Comment by aositeluofu** [comment]
Hi,I would like to know how to let the robot arm move to grasp the red box.I am still new to this ROS area.Can you tell me what launch file should I execute? looking forward to your reply

**Comment by aositeluofu** [comment]
@weiwuhuhu Hi,I would like to know how to let the robot arm move to grasp the red box.I am still new to this ROS area.Can you tell me what launch file should I execute? looking forward to your reply

**Comment by learningxiaobai** [comment]
> I got it, one step i missed.Thank you LiHuang, you are so cool!!!

hello，which steps you missed？my robot is static
